### PR TITLE
Tag fetch

### PR DESCRIPTION
**Pull request by wasade**
Two additions here:

- being able to get the feature IDs for a given sample or set of samples
- retrieval of tagged metadata (e.g., preparation information)

### CODE REVIEW

**Comment by wasade** [comment]
I don't understand why the commit history went completely bonkers, I'll see if I can fix. I pulled down to different base so that may have caused all this

**Comment by antgonza** [comment]
@wasade, I think it will be great if you could add more documentation and/or examples of how this works. For example, I think this adds prep information to a sample but doesn't account for samples that have multiple preparations ...

**Comment by wasade** [comment]
This doesn't make any changes to the loading methods which are discussed in
detail in the respective docstrings and the read me. This just allows for
the retrieval of preparation specific metadata.

**Comment by wasade** [comment]
Tags may be limitedly discussed in the read me (few users are loading
data). But in my opinion, the request is out of scope since the focus of
the PR and immediate need is the retrieval of data already supported by the
data model; no changes to the data model are necessary nor are changes
needed in the methods which load the data

**Comment by RNAer** [comment]
code looks good to me!

**Comment by antgonza** [comment]
I don't follow the changes and if this will have issues with multiple preps; thus, if this adds the feature requests, please @RNAer merge.

**Comment by antgonza** [comment]
After offline conversation with @wasade, I believe that this adds the functionality that @RNAer is looking for; and Zech has already approved the changes. Thus, merging.

**Comment by RNAer** [comment]
Thanks!

**Pull request merged**
